image: Visual Studio 2019
version: 1.0.{build}
configuration: Release

init:
- if "%APPVEYOR_REPO_NAME%" == "JeremyAnsel/JeremyAnsel.HLSL.Targets" if "%APPVEYOR_REPO_BRANCH%"=="master" if not defined APPVEYOR_PULL_REQUEST_NUMBER set DEPLOY=True

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'

nuget:
  disable_publish_on_pr: true

before_build:
- nuget restore JeremyAnsel.HLSL.Targets\JeremyAnsel.HLSL.Targets.sln

build:
  project: JeremyAnsel.HLSL.Targets\JeremyAnsel.HLSL.Targets.sln
  publish_nuget: true
  verbosity: minimal

deploy:
- provider: NuGet
  api_key:
    secure: ez3RLsSaraf05zX77AqWyz+gYbT+5eM7jdIq7Fv43DXPp5+YscPbW5yb7owDfyHd
  skip_symbols: true
  on:
    branch: master
    DEPLOY: True
